apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: valkon
  name: valkon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkon
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: valkon
    spec:
      serviceAccount: valkon-sa
      containers:
      - image: viveksinghggits/valkontroller:0.2.0
        name: valkontroller
        args:
        - --tls-cert-file=/var/run/webhook/serving-cert/tls.crt
        - --tls-private-key-file=/var/run/webhook/serving-cert/tls.key
        - --v=4
        resources: {}
        volumeMounts:
          - name: serving-cert
            mountPath: /var/run/webhook/serving-cert
      volumes:
        - name: serving-cert
          secret:
            secretName: certs
status: {}
