apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: vk-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vk-role
subjects:
- kind: ServiceAccount
  name: valkon-sa
  namespace: default
